### ISSUE TITLE
Conformance Tests Kokoro job is failing

### ISSUE THREAD

**Issue by frankyn** [googleapis/conformance-tests#46]
Looks like PRs have been blocked since March: https://github.com/googleapis/conformance-tests/pull/43

Failure:

```
.kokoro/validator.sh 
/tmp ~/Documents/conformance-tests
Cloning into 'googleapis'...
remote: Enumerating objects: 5917, done.
remote: Counting objects: 100% (5917/5917), done.
remote: Compressing objects: 100% (2198/2198), done.
remote: Total 5917 (delta 4385), reused 4175 (delta 3616), pack-reused 0
Receiving objects: 100% (5917/5917), 4.13 MiB | 3.88 MiB/s, done.
Resolving deltas: 100% (4385/4385), done.
~/Documents/conformance-tests
~/Documents/conformance-tests/storage/v1 ~/Documents/conformance-tests
/go/include: warning: directory does not exist.
protoc-gen-go: unable to determine Go import path for "google/cloud/conformance/storage/v1/tests.proto"

Please specify either:
        • a "go_package" option in the .proto source file, or
        • a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
```

**Comment by frankyn** [comment]
Hi @tbpg and @codyoss,

@tritone recommended I pull y'all in on what we could potentially do to unblock the kokoro failures. (I'm going on leave so Chris will be taking my place, just wanted to to start the thread). 

Cheers!

**Comment by tbpg** [comment]
The `protoc` invocation is here: https://github.com/googleapis/conformance-tests/blob/e128d775153634f7ae3abfdd5aa6eeb74710086f/.kokoro/validator.sh#L42-L46

The proto gets imported here: https://github.com/googleapis/conformance-tests/blob/e128d775153634f7ae3abfdd5aa6eeb74710086f/storage/v1/validator.go#L25

We shouldn't be using a relative import path. We should probably put a `go.mod` in the root of the directory and use a real import path (`github.com/googleapis/conformance-tests` plus whatever the proto is).

Then we can pass the import path to `protoc` as described in the error.

I don't know why the proto paths are the way they are (https://github.com/googleapis/conformance-tests/blob/master/storage/v1/proto/google/cloud/conformance/storage/v1/tests.proto). Why do we need the `proto/google/cloud/conformance/storage/v1` part of the path? Is it relevant somehow? Would be fine to keep, it's just surprisingly long. It matches the proto package declared in the .proto file: https://github.com/googleapis/conformance-tests/blob/e128d775153634f7ae3abfdd5aa6eeb74710086f/storage/v1/proto/google/cloud/conformance/storage/v1/tests.proto#L17

**Comment by tbpg** [comment]
I sent #47 to hopefully get everything running again.
