### ISSUE TITLE
[Discussion] Conformance test artifact consumption

### ISSUE THREAD

**Issue by BenWhitehead** [googleapis/conformance-tests#7]
There are currently a number of questions related to consumption of conformance test artifacts in the various supported languages.

In this issues I'd like to collect some information from maintainers of `google-cloud-*` libraries, and have them weigh in on what could be better.

### Questions
1. Once firestore tests are moved to json from textproto/binproto will your language continue to use the protobuf defined types or switch to using json directly?
2. Is your project using the protobuf defined types for the `storage/v1` tests?
    * Why or why not?
3. What would be the easiest way for your language to consome artifacts for conformance tests?
    * Possible means of consumption I've heard
        * git submodule
        * copy-paste from git repo
        * tarball with artifacts zipped up it
        * artifacts hosted on a cdn and downloaded
        * per-language package manager integration
4. When there are new tests added to conformance tests what could make it easier for you to update your artifacts?

**Comment by jadekler** [comment]
Go:

1. Protobuf.
2. Yes. [1]
3. Copy paste.
4. Easier than what? o.O Than the current "email me when changes occur"? If so, nothing comes to mind as a consumer. Copy paste on notification has served us well.

1: The "why" of this is asking "why use protos", which has a big answer. Some of the quick responses are type safety, consistent schema, and auto-generated mappable objects.

**Comment by jskeet** [comment]
C#:

1. Once the Firestore tests are moved, I'll definitely use the JSON - but loading it *via* the protobuf messages. (It's not like we're stopping using protos.) I'd personally prefer for the JSON files to be the *only* representation of the data in the repo.

2. Yes, we're using protos for Storage tests.

3. We're using a submodule, so it's easier to update reliably - we'll easily be able to see when we're behind, and by which commits.

4. While we *could* automate "there's been a change in the tests repo; run a shell script in the C# repo and create a PR if necessary" I'm not sure it's worth it. An automated email when there's a change would be welcome though.

**Comment by jdpedrie** [comment]
PHP:

1. We'll switch over to JSON and likely fully discontinue use of the protos.
2. No, currently we rely on the old JSON file taken from C#.
3. No strong preference except I'd prefer not to use submodules. We've used copy/paste for Firestore, but it's easy for those to fall behind. A downloadable archive would be nice.

**Comment by quartzmo** [comment]
Ruby:

1. We'll attempt to switch over to JSON.
2. No, currently we rely on the old JSON file taken from C#.
3. copy-paste, or we can try git submodules
4. An email when there's a change.

**Comment by quartzmo** [comment]
Any suggestions for best practices to keep the tests updated when using git submodules? Should CI call `git submodule update --remote` in each test run to ensure that the latest test data is used? Or should the approach be more conservative, pinning the submodule to a stable commit or branch? (from googleapis/google-cloud-ruby#3516)

**Comment by jskeet** [comment]
@quartzmo: For C#, we're not updating implicitly, but we have a [script](https://github.com/googleapis/google-cloud-dotnet/blob/master/updateconformancetests.sh) which updates the remote and rebuilds the protos. We'd then commit the result of that. (For Ruby you may *just* need to do the update, if you don't have any other steps.)

It's always feasible for new tests to be added to the conformance test repo, and those may be ahead of the implementation in some languages - if you implicitly update the submodule, I can see that leading to frequent CI breakages. Doing it explicitly means you can run the tests and potentially skip some for the moment if there's pending work. (Alternatively, new tests may mean writing new test infrastructure to consume those tests.)

It's worth being subscribed to the conformance test repo to make sure you hear about changes though. In a perfect world, you might want automation to file an issue if the submodule is more than a few days out of date, but that's probably overkill for now :)

**Comment by quartzmo** [comment]
Because separate submodules for each package in our monorepo would mean all of conformance-tests in each package directory, we decided in Ruby to copy the files rather than use git submodules. See googleapis/google-cloud-ruby#3525.

**Comment by jskeet** [comment]
@quartzmo: Why would you need to have a submodule in each package? Any reason you don't put it in the root directory? (Alternatively, one submodule per package that actually *uses* conformance tests probably wouldn't be too bad - and it's not like this takes any space in GitHub itself.)

If copying the files works for you, I'm not going to push you to do anything else - just curious why submodules really aren't practical for you.

**Comment by quartzmo** [comment]
As @blowmage [commented](https://github.com/googleapis/google-cloud-ruby/pull/3516#discussion_r296023451):

> If you have separate submodules, each gem can pin to a different commit so that each gem can be upgraded independently.

Once we concluded that the version of the submodule(s) would be pinned, we no longer saw as much value in having them, since updates would be manual in any case.

**Comment by BenWhitehead** [comment]
Closing this as it seems everyone is using sub-modules or copy-paste and has a working process for their respective projects.
